<?php
ob_start(); // Start output buffering

require_once('vendor/autoload.php'); // Include the Composer autoload file
include 'config.php'; // Include the database connection

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Alerts Report');
$pdf->SetSubject('Report of all alerts');
$pdf->SetKeywords('TCPDF, PDF, report, alerts');

// Set default header data with logo
$pdf->SetHeaderData('logo.png', 30, 'Alerts Report', 'Generated by Alert Kenya');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Fetch alerts from the database
$stmt = $conn->prepare("SELECT id, title, description, location, created_at FROM alerts ORDER BY created_at DESC");
$stmt->execute();
$result = $stmt->get_result();

// Create an HTML table with the data
$html = '<h1>Alerts Report</h1>';
$html .= '<table border="1" cellspacing="3" cellpadding="4">';
$html .= '<tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Location</th>
            <th>Created At</th>
          </tr>';

while ($row = $result->fetch_assoc()) {
    $html .= '<tr>
                <td>' . htmlspecialchars($row['id']) . '</td>
                <td>' . htmlspecialchars($row['title']) . '</td>
                <td>' . htmlspecialchars($row['description']) . '</td>
                <td>' . htmlspecialchars($row['location']) . '</td>
                <td>' . htmlspecialchars($row['created_at']) . '</td>
              </tr>';
}

$html .= '</table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
ob_clean(); // Clear the output buffer before sending the PDF
$pdf->Output('alerts_report.pdf', 'D');

// Close the database connection
$stmt->close();
$conn->close();

ob_end_flush(); // End and flush the output buffer
?>
